### ISSUE TITLE
Not working, "com.github.tukenuke.tuske.util.EffectSection.hasDelayBefore" is null

### ISSUE THREAD

**Issue by szcs0** [szumielxd/TuSKe#1]
Don't understand whats going on.... [TuSKe 1.10.0]
https://pastebin.com/ANPVynfu

Main Issue:
`Stack trace: [16:27:50 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "com.github.tukenuke.tuske.util.EffectSection.hasDelayBefore" is null`

Works when I Don't add `to run:`
Not working - `format gui slot 0 of player with diamond sword to run:`
Works - `format gui slot 0 of player with diamond sword`

**Comment by PrymeOS** [comment]
I think the main issue is
`Stack trace:
[16:27:50 ERROR]: #!#! java.lang.NullPointerException:
Cannot invoke "java.lang.reflect.Field.get(Object)" because "com.github.tukenuke.tuske.util.EffectSection.hasDelayBefore" is null`

**Comment by PrymeOS** [comment]
It works when i dont add `to run:` in it's sentencelike 
`format gui slot 0 of player with diamond sword to run:`
and works when its
`format gui slot 0 of player with diamond sword`

**Comment by szumielxd** [comment]
As a replacemenet you can use `format gui slot 0 of player with diamond sword to run function example_function(p: player)` for now.

**Comment by szcs0** [comment]
> As a replacemenet you can use `format gui slot 0 of player with diamond sword to run function example_function(p: player)` for now.

k

**Comment by szumielxd** [comment]
Fixed
