### ISSUE TITLE
Not working correctly

### ISSUE THREAD

**Issue by Griffeng** [szumielxd/TuSKe#2]
Server version: 1.17.1 PaperMC

This is probably caused by me using 1.17.1 can't seem to find any evidence that 1.17 support is implemented. 

Error from console: https://cdn.gr1ffen.dk/AGpwEb.txt

**Comment by szcs0** [comment]
Probably working on it already.
[Exact Issue](https://github.com/szumielxd/TuSKe/issues/1)
