### ISSUE TITLE
Are you able to fix TuSKe for Skript 1.18 ? :O

### ISSUE THREAD

**Issue by bloggy** [szumielxd/TuSKe#4]
Skript (for 1.18) is available but TuSKe does not seem to work anymore (errors on startup). Do you think you'd be able to fix this? :-O
That would be awesome !!!!

Errors in console on startup:
https://pastebin.com/RSs5QgCZ

I am using the latest skript version from skunity's discord: 
https://i.imgur.com/b1fvcaK.png

Thanks for your help!

**Comment by szumielxd** [comment]
Are you sure, you use correct version of TuSKe?
```
[14:28:04] [Server thread/ERROR]: #!#! Here is full list of them:
[14:28:04] [Server thread/ERROR]: #!#! TuSKe v1.9-Thefirstalpha-Patch-1-MH-1 (github.com/Tuke-Nuke/TuSKe) 
[14:28:04] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
```
I don't remember any of my releases named **TuSKe v1.9-Thefirstalpha-Patch-1-MH-1**.

**Comment by szumielxd** [comment]
It looks like long-lived missformtting of the RegEx expression. Fixed

**Comment by bloggy** [comment]
> It looks like long-lived missformtting of the RegEx expression. Fixed

Thank you. It loads without errors now, but there is another issue, going to open new ticket for it
